### ISSUE TITLE
Problem with the app - Photobucket 

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-android-sdk#147]
Hi guys!

Could you please see below and advise:
"I tried to use you 80% off coupon code yesterday and I wasn't able to. I followed the link in my email, it took me to your website, and it simply says the print shop can now be accessed from your app . So I downloaded the app and tried to create my canvas print, and got a failure notice. I'm sending a screenshot to show you. I keep getting this failure notice for the past 2 days."
![app issue](https://cloud.githubusercontent.com/assets/8796232/10016245/c5fd5ba0-6125-11e5-870c-c52a690412d9.png)

Thanks!

**Comment by vladopajic** [comment]
Hello Jovana,

This message simply means that Photobucket's photo source is temporarily unavailable. Unavailability of photo source is caused due to Photobuckets API. Other photo sources should function correctly (Phone, Facebook, etc...). 

Unfortunately, we cant assist Maggie, I assume, much in this case. She can try to use photos from other sources until Photobucket's photo sources starts functioning correctly.

Note that I have tried Photobucket App and Photobucket's photo source works for me.

Regards,
Vlado

**Comment by jovana-kovacevic** [comment]
Hi Vlado!

Thanks, I'll let her know!

Best,
Jovana
