### ISSUE TITLE
App lets you select more than required images - Keepy

### ISSUE THREAD

**Issue by Debysh** [printdotio/printio-android-sdk#148]
Steps to reproduce:
Select type of product Canvas Mini - "Create it" > select size > select 2 items 
Expected Result: User should be able to select only 1 item (as appropriate for the selected product) -

**Comment by tobiasfrier** [comment]
@Debysh thanks for bring this to our attention. We will get to it.

**Comment by vladopajic** [comment]
Hello @Debysh,

Actually, it is not expected result. We intentionally allow user to select more photos that layout could support. This is because we want to reduce navigation between select images screen and product customization screen. One case is that user could have similar photos and he wants to choose one but he is not sure what photo will suit the layout more.

Regards,
Vlado

**Comment by Debysh** [comment]
Thanks for the clarification Vlado,

Deby
